[project]
authors = ["Cordero Core <127983572+uwcdc@users.noreply.github.com>"]
name = "pydbmodel"
version = "0.1.0"
description = "Convert SQLAlchemy/SQLModel into DBML, and the other way around! 🎉"

# Ensure dependencies are installed from PyPI instead of Conda
channels = ["conda-forge"]

# Define compatible platforms
platforms = ["linux-64", "osx-arm64", "osx-64"]

# Define dependencies with explicit versions
[dependencies]
sqlmodel = ">=0.0.24,<0.0.25"
sqlalchemy = ">=2.0.39,<3"
pydantic = ">=2.10.6,<3"
typer = ">=0.15.2,<0.16"
rich = ">=13.9.4,<14"
autoflake = ">=1.4,<2"
isort = ">=5.9.3,<6"
black = ">=20.8b1,<21"
pytest = ">=8.3.5,<9"

# Define custom tasks
[tasks]
test = "pytest"
